name: payjoin_flutter
description: "A Flutter library for the [Payjoin Dev Kit](https://payjoindevkit.org/)"
version: 0.21.0
homepage: https://github.com/LtbLightning/payjoin-flutter

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.1
  ffi: ^2.0.1
  flutter_rust_bridge: "^2.0.0"
  freezed_annotation: ^2.2.0
  meta: ^1.10.0
  uuid: ^4.2.1

dev_dependencies:
  ffigen: ^9.0.0
  freezed: ^2.3.5
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
